apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-species-prediction-app
  labels:
    app: iris-species-prediction-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iris-species-prediction-app
  template:
    metadata:
      labels:
        app: iris-species-prediction-app
    spec:
      containers:
        - name: iris
          image: homrighoused/iris-prediction-ml:1.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: iris-service
  labels:
    app: iris-species-prediction-app
spec:
  type: LoadBalancer    # For minikube: `minikube service iris-service`
  selector:
    app: iris-species-prediction-app
  ports:
    - name: http
      port: 80          # external port users hit
      targetPort: 5000  # container port exposed by Gunicorn
